# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-04-30T21:36:24+00:00

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, RootModel


class TimeTrackerProtocolSchema(RootModel[Any]):
    root: Any = Field(
        ...,
        description='Schema definition for TimeTracker protocol messages',
        title='TimeTracker Protocol Schema',
    )


class StorageType(RootModel[Literal['file', 'database', 'cloud', 'memory']]):
    root: Literal['file', 'database', 'cloud', 'memory'] = Field(
        ..., description='Type of storage backend', title='StorageType'
    )


class MessageType(
    RootModel[
        Literal[
            'GET_TIME_ENTRIES',
            'ADD_TIME_ENTRY',
            'UPDATE_TIME_ENTRY',
            'DELETE_TIME_ENTRY',
            'GET_CATEGORIES',
            'LOAD_STORAGE',
            'SAVE_STORAGE',
            'SAVE_STORAGE_AS',
            'NEW_STORAGE',
            'GET_CURRENT_STORAGE',
            'GET_STORAGE_LIST',
            'HAS_UNSAVED_CHANGES',
            'CLEAR_STORAGE',
            'SUCCESS',
            'ERROR',
        ]
    ]
):
    root: Literal[
        'GET_TIME_ENTRIES',
        'ADD_TIME_ENTRY',
        'UPDATE_TIME_ENTRY',
        'DELETE_TIME_ENTRY',
        'GET_CATEGORIES',
        'LOAD_STORAGE',
        'SAVE_STORAGE',
        'SAVE_STORAGE_AS',
        'NEW_STORAGE',
        'GET_CURRENT_STORAGE',
        'GET_STORAGE_LIST',
        'HAS_UNSAVED_CHANGES',
        'CLEAR_STORAGE',
        'SUCCESS',
        'ERROR',
    ] = Field(..., description='Type of the message', title='MessageType')


class FilterStorageType(
    RootModel[Literal['file', 'database', 'cloud', 'memory', 'all']]
):
    root: Literal['file', 'database', 'cloud', 'memory', 'all'] = Field(
        ..., description='Filter by storage type', title='FilterStorageType'
    )


class TimeEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., description='Unique identifier for the time entry')
    start_time: datetime = Field(..., description='Start time of the entry')
    end_time: Optional[datetime] = Field(
        None, description='End time of the entry, null if ongoing'
    )
    description: Optional[str] = Field(
        None, description='Optional description of the time entry'
    )
    category: Optional[str] = Field(
        None, description='Optional category of the time entry'
    )


class Category(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str = Field(..., description='Unique identifier for the category')
    name: str = Field(..., description='Display name of the category')
    color: Optional[str] = Field(None, description='Optional color for the category')


class StorageInfo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    storage_id: str = Field(..., description='Identifier for the storage location')
    display_name: Optional[str] = Field(
        None, description='User-friendly name for the storage'
    )
    storage_type: StorageType
    modified: Optional[bool] = Field(
        None, description='Whether there are unsaved changes'
    )
    metadata: Optional[Dict[str, Any]] = Field(
        None, description='Additional metadata about the storage'
    )


class BaseMessage(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    msg_type: MessageType
    msg_id: str = Field(..., description='Unique identifier for the message')


class Request(BaseMessage):
    payload: Optional[Dict[str, Any]] = Field(None, description='Request payload data')


class Response(BaseMessage):
    request_id: str = Field(
        ..., description='ID of the request this response corresponds to'
    )
    success: bool = Field(..., description='Whether the request was successful')
    error_message: Optional[str] = Field(
        None, description='Error message if success is false'
    )
    payload: Optional[Dict[str, Any]] = Field(None, description='Response payload data')


class TimeEntriesFilter(BaseModel):
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    category: Optional[str] = None


class GetTimeEntriesRequest(Request):
    msg_type: Literal['GET_TIME_ENTRIES'] = 'GET_TIME_ENTRIES'
    payload: Optional[TimeEntriesFilter] = Field(None, title='TimeEntriesFilter')


class TimeEntriesPayload(BaseModel):
    time_entries: List[TimeEntry]


class GetTimeEntriesResponse(Response):
    msg_type: Optional[Literal['SUCCESS', 'ERROR']] = None
    payload: Optional[TimeEntriesPayload] = Field(None, title='TimeEntriesPayload')


class TimeEntryPayload(BaseModel):
    time_entry: TimeEntry


class AddTimeEntryRequest(Request):
    msg_type: Optional[Literal['ADD_TIME_ENTRY']] = None
    payload: Optional[TimeEntryPayload] = Field(None, title='TimeEntryPayload')


class AddTimeEntryResponse(Response):
    msg_type: Optional[Literal['SUCCESS', 'ERROR']] = None
    payload: Optional[TimeEntryPayload] = Field(None, title='TimeEntryPayload')


class UpdateTimeEntryRequest(Request):
    msg_type: Optional[Literal['UPDATE_TIME_ENTRY']] = None
    payload: Optional[TimeEntryPayload] = Field(None, title='TimeEntryPayload')


class EntryIdPayload(BaseModel):
    entry_id: str


class DeleteTimeEntryRequest(Request):
    msg_type: Optional[Literal['DELETE_TIME_ENTRY']] = None
    payload: Optional[EntryIdPayload] = Field(None, title='EntryIdPayload')


class GetCategoriesRequest(Request):
    msg_type: Optional[Literal['GET_CATEGORIES']] = None
    payload: Optional[Dict[str, Any]] = Field(None, title='EmptyPayload')


class CategoriesPayload(BaseModel):
    categories: List[Category]


class GetCategoriesResponse(Response):
    msg_type: Optional[Literal['SUCCESS', 'ERROR']] = None
    payload: Optional[CategoriesPayload] = Field(None, title='CategoriesPayload')


class LoadStoragePayload(BaseModel):
    storage_id: str = Field(
        ..., description='Identifier for the storage to load (e.g., file path)'
    )
    storage_type: Optional[StorageType] = None


class LoadStorageRequest(Request):
    msg_type: Literal['LOAD_STORAGE'] = 'LOAD_STORAGE'
    payload: Optional[LoadStoragePayload] = Field(None, title='LoadStoragePayload')


class StorageIdPayload(BaseModel):
    storage_id: Optional[str] = Field(
        None, description='Identifier for the current storage'
    )


class SaveStorageRequest(Request):
    msg_type: Optional[Literal['SAVE_STORAGE']] = None
    payload: Optional[StorageIdPayload] = Field(None, title='StorageIdPayload')


class SaveStorageAsPayload(BaseModel):
    storage_id: str = Field(..., description='Identifier for the new storage location')
    storage_type: Optional[StorageType] = None


class SaveStorageAsRequest(Request):
    msg_type: Optional[Literal['SAVE_STORAGE_AS']] = None
    payload: Optional[SaveStorageAsPayload] = Field(None, title='SaveStorageAsPayload')


class StorageTypePayload(BaseModel):
    storage_type: Optional[StorageType] = None


class NewStorageRequest(Request):
    msg_type: Optional[Literal['NEW_STORAGE']] = None
    payload: Optional[StorageTypePayload] = Field(None, title='StorageTypePayload')


class GetCurrentStorageRequest(Request):
    msg_type: Optional[Literal['GET_CURRENT_STORAGE']] = None


class StorageInfoPayload(BaseModel):
    storage_info: Optional[StorageInfo] = None


class GetCurrentStorageResponse(Response):
    msg_type: Optional[Literal['SUCCESS', 'ERROR']] = None
    payload: Optional[StorageInfoPayload] = Field(None, title='StorageInfoPayload')


class StorageListFilterPayload(BaseModel):
    storage_type: Optional[FilterStorageType] = None
    limit: Optional[int] = Field(None, description='Maximum number of items to return')


class GetStorageListRequest(Request):
    msg_type: Literal['GET_STORAGE_LIST'] = 'GET_STORAGE_LIST'
    payload: Optional[StorageListFilterPayload] = Field(
        None, title='StorageListFilterPayload'
    )


class StorageListPayload(BaseModel):
    storage_list: List[StorageInfo]


class GetStorageListResponse(Response):
    msg_type: Optional[Literal['SUCCESS', 'ERROR']] = None
    payload: Optional[StorageListPayload] = Field(None, title='StorageListPayload')


class HasUnsavedChangesRequest(Request):
    msg_type: Optional[Literal['HAS_UNSAVED_CHANGES']] = None


class UnsavedChangesPayload(BaseModel):
    has_unsaved_changes: bool


class HasUnsavedChangesResponse(Response):
    msg_type: Optional[Literal['SUCCESS', 'ERROR']] = None
    payload: Optional[UnsavedChangesPayload] = Field(
        None, title='UnsavedChangesPayload'
    )


class ClearStorageRequest(Request):
    msg_type: Optional[Literal['CLEAR_STORAGE']] = None


class StorageResponse(Response):
    msg_type: Optional[Literal['SUCCESS', 'ERROR']] = None
    payload: Optional[StorageInfoPayload] = Field(None, title='StorageInfoPayload')
